# Generated by Django 5.2.1 on 2025-05-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("precio", models.FloatField()),
                ("tallas_disponibles", models.JSONField(default=list)),
                ("url_imagen", models.URLField(max_length=300)),
                ("proveedor", models.CharField(max_length=100)),
                ("valoracion", models.FloatField()),
                ("comentario", models.JSONField(default=list)),
            ],
        ),
    ]
