# Generated by Django 5.2.1 on 2025-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="comentario",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="url_imagen",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="valoracion",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
